# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - '*'
      - '!DocsReferences'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo running PWD
          pwd
          mkdir html
          cp test.html html/test2.html

      #name: push docs to docsreferences->submodule
      - uses: actions/checkout@v2
        with:
          ref: DocsReferences
          submodules: 'true'
      - run: |
          date > generated.txt
          git config --global user.name "Alex Anker"
          git config --global user.email "alex.anker@epcpower.com"
          git config user.name "Alex Anker"
          git config user.email "alex.anker@epcpower.com"
          pwd
          git fetch
          #git checkout DocsReferences
          #git submodule update --init
          ls
          ls GeneratedDox
          cd GeneratedDox
          git branch
          git checkout main
          pwd
          
          #cp ../generated.txt generated.txt
          #git add .
          #git commit -m "generated"
          #git push
          
          #cp ../html/test2.html test2.html
          #git add test2.html
          #git commit -m "adding test2"
          #git push
          #git push https://${{ secrets.GITHUB_TOKEN }}@github.com/epcAnker/GeneratedDox.git
          #cd ..
          #git add GeneratedDox
          #git commit -m "updating GeneratedDox Ref"
          #git push
          cd ..
          git add generated.txt
          git commit -m "gen"
          git push
